### PR TITLE
session created

### PR DESCRIPTION
**Pull request by hamzzy**
to be use in the controller 
``from bast import  session
   sess=session.FileSession()
   sess_mem=session.MemorySession()
   class ExampleController(Controller):
    def index(self):
          
        sess_mem.put("version","v 1.0")
        sess.put('email',"bast framework")
        data = sess.get('email')
        mem=sess.get("version")
        self.view('index.html', {'data':data,'mem',mem})

    def test(self):
        data = sess.get('email')
        self.view('hello.html',{'data':data}
 file can be access globaly bt memory localy in a function that exist in a controller

### CODE REVIEW

**Comment by moluwole** [comment]
Can you make it such that the session would be set from the config file? I mean, the user should set from the config file whether he/she would like to make use of Memory, File or Redis for the session. Just like Laravel....

**Comment by moluwole** [comment]
and can you please merge with the develop branch first instead of master. We will merge it with `master` as soon as we through

**Comment by hamzzy** [comment]
sure can do that but kind off busy will do that

**Comment by moluwole** [comment]
Cool bro. As soon as you have the time, just do so

**Pull request closed without merging**
